# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[username]
format = " [❯ $user]($style)@"
show_always = true
style_user = "green"
style_root = "red"

[hostname]
disabled = false
format = "[$hostname]($style) in "
ssh_only = false
trim_at = "-"
style = "bold red"

[sudo]
disabled = false

[directory]
style = "purple"
truncate_to_repo = true
truncation_length = 0
truncation_symbol = "repo: "


[character]
error_symbol = " [×](bold red)"
success_symbol = " [➜](bold red)"

[cmd_duration]
disabled = false
format = "took [$duration]($style)"
min_time = 1
style = "purple"
